import { Spot } from "@/types/spot";

export async function getAllSpots(user_id: string): Promise<Spot[]> {
  try {
    const response = await fetch(`/api/spots?user_id=${user_id}`, {
      method: "GET",
      headers: { "Content-Type": "application/json" },
      credentials: 'include',  // Include cookies in request
    });
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    const data = await response.json();
    return data;
  }
  catch (error) {
    console.error(`Error fetching spots: ${error}`);
    return [];
  }
}
export async function loadspots(): Promise<Spot[]> {
  try {
    const response = await fetch("/api/spots", {
      method: "GET",
      headers: { "Content-Type": "application/json" },
      credentials: 'include',  // Include cookies in request
    });
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    const data = await response.json();
    return data;
  }
  catch (error) {
    console.error(`Error fetching spots: ${error}`);
    return [];
  }
}

export async function getSpotById(spotId: string): Promise<Spot | null> {
  try {
    const response = await fetch(`/api/spots/${spotId}`, {
      method: "GET",
      headers: { "Content-Type": "application/json" },
      credentials: 'include',  // Include cookies in request
    });
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    const data = await response.json();
    return data;
  }
  catch (error) {
    console.error(`Error fetching spots: ${error}`);
    return null;
  }
}

// IDs are automatically generated by supabase. if you specify an ID, then you are updating an existing spot (or at least it will try to)
export async function saveSpot(spot: Spot): Promise<Spot | null> {
  // try {
  //   const isUpdate = spot.id;
  //   const method = isUpdate ? 'PUT' : 'POST';
  //   const url = isUpdate ? `/api/spots/${spot.id}` : '/api/spots';
  //   const response = await fetch(url, {
  //     method,
  //     headers: { 'Content-Type': 'application/json' },
  //     body: JSON.stringify(spot),
  //     credentials: 'include'
  //   })
  //   if (!response.ok) {
  //     throw new Error(`HTTP error! status: ${response.status}`);
  //   }
  //   const data = await response.json();
  //   return data;
  //
  // } catch (error) {
  //   console.error(`Error saving spot: ${error}`);
  //   return null;
  // }
}
export async function deleteSpot(spotId: string): Promise<boolean> {
  //returns true (successfully deleted) or false (unable to delete).
  try {

    const response = await fetch(`/api/spots/${spotId}`, { method: 'DELETE', credentials: 'include' });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return true;

  } catch (error) {
    console.error(`Error deleting spot: ${error}`);
    return false;
  }

}
